[package]
name = "conode_protocol"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "^2.9.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }

[dev-dependencies]
snforge_std = "0.31.0"

[[target.starknet-contract]]
sierra = true
src = "src/lib.cairo"

[scripts]
test = "snforge test"
gas-report = "snforge test --gas-report"