[package]
name = "conode_protocol"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "^2.9.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
snforge_std = "^0.31.0"  
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria.git" }


[[target.starknet-contract]]
sierra = true
src = "src/lib.cairo"

[scripts]
test = "snforge test"
gas-report = "snforge test --gas-report"