[package]
name = "conode_protocol"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.3.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", branch = "main" } # Changed to main branch

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
assert_macros = "2.8.5"

[[target.starknet-contract]]
sierra = true
src = "src/lib.cairo" 

[scripts]
test = "snforge test"